name: build

on:
  push:
    branches: [main]
  pull_request:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@nightly
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --check
      - run: cargo clippy --lib --tests -- -D warnings
      - run: cargo test
      - run: RUSTDOCFLAGS="-D warnings" cargo doc --no-deps
      - run: cargo +nightly bench
